### ISSUE TITLE
Time keeps ':00' on the hour '3:00'

### ISSUE THREAD

**Issue by powpow12** [waynestate/apdatetime#2]
Per the test [here ](https://github.com/waynestate/apdatetime/blob/fec2313af0dfa6beadf4014f7fa8b4317b76785e/tests/APDateTimeTest.php#L33)

```
$datetime = apdatetime(date('g:i a', strtotime('08:00:00')));
$this->assertEquals('8:00 a.m.', $datetime);
```
My understanding is this is not correct and it should be `8 a.m.`. 

I don't know if there is a defacto AP Style guide but here are some resources:
* [ If it’s an exact hour, no “:00″ is required.](https://journalistsresource.org/home/ap-style-basics/)
* [Don't use colons for time on the hour](https://coschedule.com/blog/ap-style-cheat-sheet#months--days----times)
* [Use a colon to separate hours from minutes, but do not use :00. Examples: 1 p.m., 3:30 a.m.](https://owl.purdue.edu/owl/subject_specific_writing/journalism_and_journalistic_writing/ap_style.html)

**Comment by nickdenardis** [comment]
Thanks for this report! We are reviewing and will have an update soon here. 😊

**Comment by nickdenardis** [comment]
Resolved.
